ktor:
  application:
    modules:
      - dev.aoriani.ecomm.ApplicationKt.module
  deployment:
    port: "$PORT:8080"

ecomm:
  database:
    url: "jdbc:sqlite:./data/products.db"
    driver: "org.sqlite.JDBC"
  logging:
    level: "DEBUG"

app:
  images:
    base-url: "https://aoriani.dev/static/images"

