ktor:
  application:
    modules:
      - dev.aoriani.ecomm.ApplicationKt.module
  deployment:
    port: "$PORT:8080"

ecomm:
  database:
    url: "jdbc:h2:./data/products"
    driver: "org.h2.Driver"
  logging:
    level: "DEBUG"
  mcp:
    server-name: "ecomm-mcp-server"
    server-version: "0.0.1"
  images:
    base-url: "https://api.aoriani.dev/static/images"
