ktor:
  application:
    modules:
      - dev.aoriani.ecomm.ApplicationKt.module
  deployment:
    port: "$PORT:8080"

ecomm:
  database:
    url: "r2dbc:h2:file:./data/products"
    driver: "org.h2.Driver"
  logging:
    level: "DEBUG"
  images:
    base-url: "https://aoriani.dev/static/images"
